import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  projectSidebar: [{ type: 'autogenerated', dirName: 'project' }],
  webSidebar: [{ type: 'autogenerated', dirName: 'web' }],
  networkGameSidebar: [{ type: 'autogenerated', dirName: 'networkGame' }],
  planetTechSidebar: [{ type: 'autogenerated', dirName: 'planetTech' }],
  narrativeDesignSidebar: [
    { type: 'autogenerated', dirName: 'narrativeDesign' },
  ],
  gameDesignSidebar: [{ type: 'autogenerated', dirName: 'gameDesign' }],
  creativeConceptSidebar: [
    { type: 'autogenerated', dirName: 'creativeConcept' },
  ],
  uiuxSidebar: [{ type: 'autogenerated', dirName: 'uiux' }],
  audioSidebar: [{ type: 'autogenerated', dirName: 'audio' }],
  vFXSidebar: [{ type: 'autogenerated', dirName: 'vFX' }],
  qaPlayTestSidebar: [{ type: 'autogenerated', dirName: 'qaPlayTest' }],
  cutsceneVideoSidebar: [{ type: 'autogenerated', dirName: 'cutsceneVideo' }],

  helpSidebar: [{ type: 'autogenerated', dirName: 'help' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
